deploymenttheory/terraform-provider-jamfpro

- README.md
- internal/provider/provider.go
Added support for sites and departments into the provider
> Terraform plugin sdk v2

- internal/endpoints/scripts/scripts_resource.go
- pipeline/duplicate_resources/duplicate_resources.go
Bug fixes for scripts resource state setting
> Bug fixes for scripts resource state setting

- internal/endpoints/packages/packages_helpers.go
- internal/endpoints/packages/packages_resource.go
Added 30 second time out for package uploads to allow for jamf to settle down before stating
> Update package retrieval and resource timeouts***

- internal/endpoints/computerextensionattributes/computerextensionattributes_state.go
- internal/endpoints/policies/notes.txt
Forced extension attrs to state lower case data type to stop false positive plans
> small fix to stop force positive plan loop

- internal/endpoints/computerinventorycollection/computerinventorycollection_object.go
- internal/endpoints/computerinventorycollection/computerinventorycollection_resource.go
- internal/endpoints/computerinventorycollection/computerinventorycollection_state.go
added computer inventory collection to provider
> added computer inventory collection to provider

- internal/provider/provider.go
> Update provider.go from JAMFPRO_INSTANCE_NAME to JAMFPRO_INSTANCE_FQDN

- internal/endpoints/policies/policies_resource.go
`jamfpro_policy` doesn't support import
```shell
> TF=DEBUG terraform import jamfpro_policy.microsoft_excel 343
jamfpro_policy.microsoft_excel: Importing from ID "343"...
jamfpro_policy.microsoft_excel: Import prepared!
Prepared jamfpro_policy for import
jamfpro_policy.microsoft_excel: Refreshing state... [id=343]
Import successful!
The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
> terraform state show jamfpro_policy.microsoft_excel
resource "jamfpro_policy" "microsoft_excel" {
category_id                   = 4
enabled                       = true
frequency                     = "Ongoing"
id                            = "343"
name                          = "[tf] Microsoft Excel" …
```
> add import policy

- internal/resources/macosconfigurationprofilesplist/crud.go
- internal/resources/policies/crud.go
@vbnin-jamf for help finding workaround
> Locking create threads for policies and profiles

- internal/resources/computerextensionattributes/contructor.go
- internal/resources/computerextensionattributes/resource.go
- internal/resources/computerextensionattributes/state.go
- internal/resources/computerextensionattributes/state_migration.go
Testing complete
Pre state migration
```
{
"mode": "managed",
"type": "jamfpro_computer_extension_attribute",
"name": "computer_extension_attribute_script_2",
"provider": "provider[\"terraform.local/local/jamfpro\"]",
"instances": [
{
"schema_version": 0,
"attributes": {
"data_type": "string",
"description": "An attribute collected via a script.",
"enabled": true,
"id": "5717",
"input_popup": null,
"input_script": "#!/bin/sh\n\n########## variable-ing ##########\n\n\n\nloggedInUser=$(/usr/bin/stat -f%Su \"/dev/console\")\n\n\n\n########## main process ##########\n\n\n\n# Report logged-in user.\necho \"\u003cresult\u003e$loggedInUser\u003c/result\u003e\"\n\n\n\nexit 0",
"input_type": "script",
"inventory_display": "Operating System",
"name": "pre_state_migration_test_2",
"recon_display": …
```
> Improved handling of state migration for comp ext atts

- .github/workflows/api-privileges-maintenance.yml
- .github/workflows/user-account-maintenance.yml
Added handling for the const updates
> Added handling for the const updates within validate.go as part of maintenance workflow

- internal/resources/common/jamfprivileges/validate.go
Updated comments and error logic so that we base valid permissions on the latest support jamf pro version and appends additionals in previous versions if some are found.
> Refactor privilege validation logic and update comments for clarity

- internal/resources/apiintegrations/data_source.go
needed a retry and timeout wrapper around the client to avoid
tested with numerous create,update,deletes etc with no change to logic
Fixes issues on creation or updates that would never timeout or provide error
> feat: API integration RefreshClientCredentialsByApiRoleID 

- docs/data-sources/macos_configuration_profile_plist.md
- examples/data-sources/jamfpro_macos_configuration_profile_plist/data-source.tf
- internal/resources/macosconfigurationprofilesplist/data_source.go
updated example to reflect provider behaviour
> fix: to macos plist data source example

- .github/workflows/generate-docs.yml
comment was left in, remedying that
> fix: remove debug commented line

- docs/resources/local_admin_password_settings.md
- docs/resources/user_initiated_enrollment_settings.md
- examples/resources/jamfpro_local_admin_password_settings/resource.tf
- examples/resources/jamfpro_user_initiated_enrollment_settings/resource.tf
- internal/resources/userinitiatedenrollment/constructor.go
- internal/resources/userinitiatedenrollment/resource.go
- internal/resources/userinitiatedenrollment/state.go
added missing field to resource, with updated docs and example
Fixes #666
- https://github.com/deploymenttheory/terraform-provider-jamfpro/issues/666 
- None
> fix: Add flushSoftwareUpdatePlans bool to jamfpro_user_initiated_enrollment_settings

- .github/workflows/jamfpro-provider-nightly-test-cleanup.yaml
CRON not triggering
fix cleanup pipeline
cron wasnt triggering
> Fix: schedule not triggering cleanup pipeline

- go.mod
- go.sum
- internal/resources/jamfconnect/crud.go
- internal/resources/userinitiatedenrollment/crud.go
- scripts/maintainence/GetJamfAppCatalogAppInstallerTitles/GetJamfAppCatalogAppInstallerTitles.go
- [ x I have verified there are no other open Pull Requests for the same update/change
> fix: Deps for SDK, small changes to support new pagination logic

- .github/workflows/jamfpro-provider-integration-test.yml
> fix: tweaked checkout to account for workflow_dispatch

- docs/data-sources/device_enrollments_public_key.md
- go.mod
- go.sum
> chore: sdk deps to latest

- .github/workflows/release-please.yml
> feat: release please actor is now a GH app

- .github/workflows/jamfpro-provider-integration-test-new.yml
- .github/workflows/jamfpro-provider-nightly-test-cleanup.yaml
- internal/resources/scripts/resource.go
> Integreation test tweaks which needd to be in main

- .github/workflows/jamfpro-provider-integration-test-new.yml
- internal/resources/scripts/resource.go
> More testing bugfixes - must be PR'ed for testing 

- .github/workflows/jamfpro-provider-integration-test-new.yml
- internal/resources/scripts/resource.go
> More tests debugging

- .github/workflows/jamfpro-provider-integration-test-new.yml
> fix: int tests debugging

- testing/action_scripts/generate_test_directory.py
> fix: test targetting bug

- docs/index.md
- examples/provider/provider.tf
> fix: typo in provider.tf

- testing/testing/accounts/provider.tf
Removed something joseph didnt like
> fix: removed offending dir

- .github/workflows/go-lint-golangci.yml
- .github/workflows/release-please.yml
- docs/index.md
- examples/provider/provider.tf
> Fix:  typos

- testing/action_scripts/.pylintrc
- testing/action_scripts/cleanup.py
- testing/action_scripts/generate_test_directory.py
- testing/action_scripts/generate_test_targets.py
- testing/action_scripts/scaffolding_static_group_computers.py
> chore: pylint rc and appeasing the monster

- .github/workflows/go-lint-golangci.yml
- .github/workflows/provider-release.yml
- .github/workflows/release-please.yml
- docs/index.md
- examples/provider/provider.tf
> fix: typos

- .github/workflows/provider-integration-test.yml
- .github/workflows/python-pylint.yml
- testing/action_scripts/.pylintrc
- testing/action_scripts/cleanup.py
- testing/action_scripts/generate_test_directory.py
- testing/action_scripts/generate_test_targets.py
- testing/action_scripts/scaffolding_static_group_computers.py
- testing/testing/accounts/provider.tf
> chore: appeasing pylint for the integration test supporting scripts

- go.mod
- go.sum
> chore(deps): sdk to latest version

- .github/workflows/pr-title-validation.yml
- scripts/pr_title_validator.py
More Robust, Case-sensitive, Python Pr title validation
> feat: More Robust, Case-sensitive, Python Pr title validation
