internal/resources/computerextensionattributes/computerextensionattributes_data_validation.go
internal/resources/computerextensionattributes/computerextensionattributes_resource.go
internal/resources/policies/policies_data_validation.go
internal/resources/policies/policies_resource.go

add scenarios for validateJamfProResourcePolicyDataFields to handle toxic (throw request conflict errors) , and handle impossible config combinations that aren't valid in the gui but don't throw a request conflict error.

Terraform plugin sdk v2

---

internal/endpoints/computergroups/computergroups_object.go
internal/endpoints/computergroups/computergroups_resource.go

This PR should fix what I was seeing in #145. After building locally, I'm able to successfully import/plan/apply without the `computers` field being added to state or updated when planning.
Oh, and I'm very new to Go so if there is a better way to achieve these checks, please modify away!

Adding checks for Smart Groups

---

internal/endpoints/computergroups/computergroups_resource.go

As on the tin. A criterion in my Jamf instance accepts this search type:
The referenced extension attribute ("Management - Shard") outputs an integer.
Strangely (due to my ignorance I imagine), when I use "greater than" for the same criterion, the GUI displays search_type "is" - but the API response shows "greater than" nonetheless. If only to avoid Jamf's GUI from lying to me, I'd like to add this search_type.
Hopefully will be able to contribute more substantially in future :)!

adds a "more than" smart group criterion search type

---

GNUmakefile
internal/endpoints/computerextensionattributes/computerextensionattributes_data_validation.go
internal/endpoints/computerextensionattributes/computerextensionattributes_resource.go
internal/endpoints/usergroups/usergroups_resource.go

* "member of" is a valid search type for smart user groups, as with smart computer groups.
* The data_type field on an extension attribute accepts "String", "Integer", or "Date".  As currently written, the validation for this field requires the value be either "String", "Integer", or an arbitrary date string matching the "Date" data_type's required format. We're not validating the actual ext attr's returned data here, ofc :), so can just delete this and use a standard string slice validation.
Here's an excerpted example API response for an attribute w/ data_type "Date":
```
{
"id": 59,
"name": "Last Munki Run",
"enabled": true,
"description": "",
"data_type": "Date",
```

Adds 'member of' search types to user groups & remove erroneous extension attribute data_type validation

---

examples/provider/provider.tf
internal/client/client_config.go
internal/endpoints/accountgroups/accountgroups_resource.go
internal/endpoints/accounts/accounts_resource.go
internal/endpoints/advancedcomputersearches/advancedcomputersearches_resource.go
internal/endpoints/advancedmobiledevicesearches/advancedmobiledevicesearches_resource.go
internal/endpoints/advancedusersearches/advancedusersearches_resource.go
internal/endpoints/allowedfileextensions/allowedfileextensions_resource.go
internal/endpoints/apiintegrations/apiintegrations_resource.go
internal/endpoints/apiroles/apiroles_resource.go
internal/endpoints/buildings/buildings_resource.go
internal/endpoints/categories/categories_resource.go
internal/endpoints/common/constants.go
internal/endpoints/computercheckin/computercheckin_resource.go
internal/endpoints/computerextensionattributes/computerextensionattributes_resource.go
internal/endpoints/computergroups/computergroups_resource.go
internal/endpoints/computerprestageenrollments/computerprestageenrollments_resource.go
internal/endpoints/departments/departments_resource.go
internal/endpoints/diskencryptionconfigurations/diskencryptionconfigurations_resource.go
internal/endpoints/dockitems/dockitems_resource.go
internal/endpoints/filesharedistributionpoints/filesharedistributionpoints_resource.go
internal/endpoints/macosconfigurationprofiles/macosconfigurationprofiles_resource.go
internal/endpoints/networksegments/networksegments_resource.go
internal/endpoints/packages/packages_resource.go
internal/endpoints/printers/printers_resource.go
internal/endpoints/scripts/scripts_resource.go
internal/endpoints/sites/sites_resource.go
internal/endpoints/usergroups/usergroups_resource.go
internal/provider/provider.go
internal/waitfor/waitfor.go

Updated resource Create timeouts to 70seconds
Added support to the provider for a cookiejar, enabled via a new `enable_cookie_jar ` setting. This enables sticky sessions. Which when enabled, allows resources to be deployed faster due to a reduced propagation wait time of 10 seconds, however this WILL lead to increased load on a single jamf pro web application (clustered or otherwise) as it handles all Terraform CRUD operations and negates any load balancing. Consequently, deploying resources enmass (e.g creating + 10 resources at a time) can cause unpredictable resource deployment / stating errors. especially on more complex resources such as macOS config profiles. If disabled, resources adhere to Jamf Cloud's default resource propagation behaviour, incorporating a 60+1-second propagation …

Added support for sticky sessions when running TF plan and applies

---

examples/macosconfigurationprofiles/resource.tf
go.mod
go.sum
internal/endpoints/computerextensionattributes/computerextensionattributes_object.go
internal/endpoints/mobiledeviceconfigurationprofiles/mobiledeviceconfigurationprofiles_state.go
internal/endpoints/scripts/scripts_object.go
internal/endpoints/scripts/scripts_resource.go
internal/endpoints/scripts/scripts_state.go

bug fixes for object construction that now no longer requires a category field to be defined in a script resource and bug fixes also for `category_id` and `category_name` so that they are only stated if they are not default values. i.e not `-1` and `NONE` respectively.

Bug fixes for script construction and stating of script category values

---

internal/endpoints/computerextensionattributes/computerextensionattributes_resource.go

The attributes `data_type` and `inventory_display` in the computerextensionattributes have default values and are reflected in the terraform schema.
The following is the simplest example of checking default values.
```sh
$ curl -X 'POST' \
'https://example.jamfcloud.com/JSSResource/computerextensionattributes/id/0' \
-H 'accept: application/xml' \
-H 'Authorization: Bearer token' \
-H 'Content-type: application/xml' \
-d '<computer_extension_attribute><name>test for terraform</name></computer_extension_attribute>'
<?xml version="1.0" encoding="UTF-8"?>
<computer_extension_attribute>
<id>35</id>
</computer_extension_attribute>
$ curl -X 'GET' \
'https://exmaple.jamfcloud.com/JSSResource/computerextensionattributes/id/35' \
-H 'accept: application/xml' \
-H 'Authorization: Bearer token' …
```

chore: Set some default values for computerextensionattributes resource

---

.github/workflows/code-check-and-tests.yaml
.github/workflows/documentation.yml
GNUmakefile
internal/endpoints/apiroles/apiroles_resource.go
internal/endpoints/computergroups/computergroups_data_validation.go

* Adds `install` and `build_override` rules to makefile.
I've been using these during local dev to make my life easier. The idea is to run `make install` to quickly update the local build. Rule also outputs the required ~/.terraformrc override config with correct path.
* Fixes a type error I see when trying to compile main:
```
internal/endpoints/apiroles/apiroles_resource.go:111:44: cannot use intID (variable of type int) as string value in argument to apiclient.Conn.GetJamfApiRoleByID
make: *** [build] Error 1
```
* Updates the computergroup validation function to accept a computers array when isSmart is true but no site is defined. 
This matches the logic used when updating state, explicated by [this comment](https://github.com/deploymenttheory/terraform-provider-jamfpro/blob/1e3f07cae2 …

Computer groups bug

---

internal/resources/usergroups/usergroups_data_validator.go

Seems this reference wasn't updated when the user group resource was updated. Causes the following crash:
```
Stack trace from the terraform-provider-jamfpro_v0.1.5 plugin:
panic: interface conversion: interface {} is nil, not []interface {}
goroutine 504 [running]:
github.com/deploymenttheory/terraform-provider-jamfpro/internal/endpoints/usergroups.validateIsSmartAttribute({0x0?, 0x0?}, 0x140008861c0, {0x0?, 0x0?})
github.com/deploymenttheory/terraform-provider-jamfpro/internal/endpoints/usergroups/usergroups_data_validator.go:33 +0x288
github.com/deploymenttheory/terraform-provider-jamfpro/internal/endpoints/usergroups.mainCustomDiffFunc({0x101429880, 0x14000904420}, 0x140008861c0, {0x10140d3a0, 0x14000268560})
github.com/deploymenttheory/terraform-provider-jamfpro/internal/endpoints/use …
```

fix key name (users -> assigned_user_ids) in user groups validator func

---

internal/resources/scripts/crud.go

Passing name causes updates to fail, since `common.Update` passes the resource ID as name parameter. Even if it passed the resource's name value, using name as a unique ID would be undesirable, no? [This was the case in previous iteration](https://github.com/deploymenttheory/terraform-provider-jamfpro/commit/c0f125beb9339a39fe3d0a7bb8f734788b88a735#diff-d19a7abf865960388fbd11af0555e09338cde6c348f25de9f60cbf11e3ed0e45L97).
```
Error: -30T01:29:44.232Z [ERROR] provider.terraform-provider-jamfpro_v0.1.6-w0de+4: Context cancelation detected, abandoning grace period: timestamp=2024-07-30T01:29:44.232Z
Error: -30T01:29:44.233Z [ERROR] provider.terraform-provider-jamfpro_v0.1.6-w0de+4: Response contains error diagnostic: @module=sdk.proto tf_rpc=ApplyResourceChange …
```

update scripts by ID, not name

---

internal/resources/computerextensionattributes/resource.go
internal/resources/computerextensionattributes/state.go

- Added logic to write lower-cased `data_type` to TF state in `extensionattributes.updateState`. 
- I didn't use a `StateFunc` because I couldn't get it to work. It is broken, and has been for 5 years (which raises concern about SDKv2 in general 😟): https://github.com/hashicorp/terraform-plugin-sdk/issues/164. (Or I've held it wrong.)
- Jamf's API does return a capitalized string for data_type - but confirmed one can POST/PUT lower case values.
- Lower cased the values in the attr's default and description.
- Also: added a relevant `SuppressDiffFunc`. Will only impact folks with pre-existing, capitalized values in state. Since the first apply w/ new `updateState` func will rewrite state and so permanently suppress such erroneous diffs, this addition isn't needed. Still good form imo. …

`jamfpro_computer_extension_attribute.data_type`: lower case in state; suppress case differences

---

docs/resources/macos_configuration_profile_plist.md
examples/resources/jamfpro_macos_configuration_profile_plist/resource.tf
internal/resources/macosconfigurationprofilesplist/data_validator.go
internal/resources/macosconfigurationprofilesplist/diff_suppress.go
internal/resources/macosconfigurationprofilesplist/resource.go

Per Hashicorp
> NOTE: CustomizeDiff does not currently support computed/"known after apply" values from other resource attributes.
This makes it impossible to use computed or otherwise gleaned plists (e.g. from dynamically created resources).
Adding a resource flag to suppress validation and format checks . Flag is optional and defaults to "true" so will not change existing functionality.
Had to moved StateFunc inside of the existing `CustomizeDiff (mainCustomDiffFunc)` with an embedded func of `normalizePayloadState`
Kept new functionality only to MacOS profiles, but no reason it cannot be included on Mobile too

Added profile plist validate flag

---

internal/resources/policies/constructor.go

In the scope of policy, if we are specifying all computers, then policy does not need any other scope.
Therefore, I have changed the validation logic to work as expected.

Fix a scope validation for policy

---

examples/resources/jamfpro_macos_configuration_profile_plist/resource.tf
internal/resources/common/configurationprofiles/plist/diffsuppression.go
internal/resources/macosconfigurationprofilesplist/constructor.go
internal/resources/macosconfigurationprofilesplist/crud.go
internal/resources/macosconfigurationprofilesplist/resource.go
internal/resources/macosconfigurationprofilesplist/state.go

+ fix for state when adding or removing the the self service block
+ removal of the ForceNew field to stop the redeployment of a config profile when a self service category is added or removed
+ simplified / improved diff suppression for returned html responses for plists
+ removed unnecessary default values for self service

Bugfix macOS config profiles - numerous bug fixes for stating, forcenew and diff suppression

---

internal/resources/staticcomputergroups/constructor.go

`resource.Computers` is always `nil`, since its instantiated at beginning of `func construct`. Checking this always prevents it from being correctly constructed from `assigned_computer_ids`. 
[Unlike](https://github.com/deploymenttheory/go-api-sdk-jamfpro/blob/main/sdk/jamfpro/classicapi_usergroups.go#L50) `ResourceUserGroup.Users`, `ResourceComputerGroup.Computers` [is a pointer](https://github.com/deploymenttheory/go-api-sdk-jamfpro/blob/main/sdk/jamfpro/classicapi_computer_groups.go#L42). (Which is optimal? I'm not sure, [but probably not pointers, sans a specific reason](https://stackoverflow.com/questions/59964619/difference-using-pointer-in-struct-fields).)

bug fix (staticcomputergroups): modifying static computer group membership always fails

---

internal/resources/computerprestageenrollments/constructor.go
internal/resources/computerprestageenrollments/state.go

When attempting to update prestages on an environment with multiple pre-existing prestages, I get the following 409 Conflict response:
```terraform
~ resource "jamfpro_computer_prestage_enrollment" "zoom_rooms" {
~ auto_advance_setup                    = false -> true
id                                    = "4"
~ install_profiles_during_setup         = false -> true
~ keep_existing_site_membership         = false -> true
~ prestage_installed_profile_ids        = [
+ "175",
+ "174",
+ "172",
+ "171",
+ "170",
+ "173",
+ "177",
]
+ region                                = "US"
+ support_email_address                 = "it+zoom-rooms@faire.com"
~ purchasing_information {
id              = "4"
~ life_expectancy = 0 -> 3
}
~ skip_setup_items {
~ display_tone       = false -> true
~ location …
```

Always use "-1" for prestage location_information, purchasing_information, and account_settings IDs

---

internal/resources/activationcode/crud.go

In the activationcode package, `SetId` is assigned the value `jamfpro_computer_checkin_singleton` on read operations, rather than `jamfpro_activation_code_singleton`. 
Purely a cosmetic bug that shows up in terraform plan output when importing the `jamfpro_activation_code` resource in an `import` block
```
~ resource "jamfpro_activation_code" "testenv_activation_code" {
~ code              = (sensitive value)
id                = "jamfpro_computer_checkin_singleton"
organization_name = "My Test Environment"
```

fix: incorrectly named SetId value in activationcode

---

.github/workflows/user-account-maintenance.yml

This commit updates the script to export Jamf Pro user account privileges. It adds functionality to extract the semantic version from the full version directory name and exports it for use in the pull request. The commit also updates the commit message and title for the automated pull request to reflect the changes made.
Changes include:
- Extracting semantic version from directory name
- Exporting version for use in pull request
- Updating commit message and title for pull request

feat: Update User Account Privileges data for Jamf Pro

---

examples/resources/jamfpro_computer_prestage_enrollments/resource.tf
internal/resources/computerprestageenrollments/constructor.go
internal/resources/computerprestageenrollments/resource.go
internal/resources/macosconfigurationprofilesplistgenerator/constructor.go
internal/resources/macosconfigurationprofilesplistgenerator/resource.go

within plist, plist_generator and computer prestage environments. 
This resolves stating issues when jamfpro returns varying approaches to sequencing id's. they can go up, then can go down, they can be random. So sets make sense.

Fix Changes made to 4 schema type lists to type sets

---

internal/resources/activationcode/resource.go

When importing a jamfpro_activation_code resource where the value of `code` is set to a sensitive variable, terraform will return the following on plan:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "jamfpro_activation_code" "this" {
~ code              = (sensitive value)
id                = "jamfpro_activation_code_singleton"
organization_name = "Example Co."
}
Plan: 1 to import, 0 to add, 1 to change, 0 to destroy.
```
TF code looks like this:
```
variable "activation_code" {
type        = string
description = "Jamf Pro activation code."
sensitive   = true
}
import {
to = jamfpro_activation_code.this
id = …
```

Draft: Add "Sensitive" attribute to JamfProActivationCode schema

---

examples/resources/jamfpro_computer_prestage_enrollments/resource.tf
internal/resources/common/helpers.go
internal/resources/common/redeployment.go
internal/resources/icons/crud.go
internal/resources/macosconfigurationprofilesplist/constructor.go
internal/resources/packages/crud.go
internal/resources/packages/helpers.go

Summary
Unified and improved the package upload verification logic across create and update operations. The changes implement a refined verification process that properly handles server-side hash calculation delays and adds new consistent cleanup of failed / corrupted package uploads.
Unified Verification Logic
- Consolidated duplicate verification code from create/update operations into a single helper function
- Removed differentiation between create/update verification behaviour
- Consistent package cleanup on any verification failure
- Improved Hash Verification Flow
- Added explicit handling for waiting on server-side hash calculation
- Retries only while hash value is empty/null
- One-time verification once hash value is present
- Non-retryable failure if hash mismatch detected
- …

feat: Refactor package create update crud

---

internal/resources/policies/resource.go
internal/resources/policies/state_migration.go
internal/resources/policies/state_payloads.go

previous iteration would some times cause tf to attempt a resource create. This fix now consistently performs a change to the existing resource state.

fix: refactor of state migration logic for Payload/UserInteraction

---

internal/resources/common/configurationprofiles/plist/shared.go

Added a post-processing step to replace escaped double quotes (`&#34;`) with standard quotes (`"`) that is added by `plist.NewEncoder`. This is causing the payloads like TCC to be improperly escaped when uploaded to Jamf. 
Previously: 
```
<key>CodeRequirement</key>
<string>identifier &#34;com.example.service&#34; and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = ABCDEFG</string>
```
Now:
```
<key>CodeRequirement</key>
<string>identifier "com.example.service" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = …
```

Prevent unnecessary escaping of double quotes

---

internal/resources/common/configurationprofiles/plist/validate.go
internal/resources/macosconfigurationprofilesplist/data_validator.go
internal/resources/macosconfigurationprofilesplist/payload_diff_suppress.go

Since jamf pro post processes any uploaded plist config profile for fields `PayloadDisplayName` & `PayloadDescription` with the config profile resource fields `name` and `description` respectively, it's therefore deterministic. Unlike uuid and other fields that are randomised.
therefore this validation ensures that what's set with what the jamf pro server expects.

feat: added plist validation for PayloadName and PayloadDescription

---

go.mod
go.sum
internal/resources/packages/crud.go

Mainly moving to latest SDK and HTTP client versions which fix the bug, please see those releases for detail.
Also changed the metadata/upload flow to be two separate retry operations with individual timeouts.

fix: package uploads no longer timeout, metadata and upload are separate operations now.

---

internal/resources/common/configurationprofiles/plist/diff_suppresion_test.go
internal/resources/common/configurationprofiles/plist/diff_suppression.go
internal/resources/common/configurationprofiles/plist/shared_test.go
internal/resources/common/configurationprofiles/plist/uuid_handling.go
internal/resources/macosconfigurationprofilesplist/constructor.go
internal/resources/macosconfigurationprofilesplist/data_validator.go
internal/resources/mobiledeviceconfigurationprofilesplist/constructor.go

- refactored logic for escaping and unescaping characters for update workflows
- fixed unit test logic
- replace html string replacement with finer grained specific handling for xml / plist / jamf pro needs
- preserves existing desired handling for " characters

fix: for '&' handling within plists for macos and mobile devices

---

internal/resources/advancedmobiledevicesearches/resource.go

Added "member of" & "not member of" to the search type validation for Advanced Mobile Device Searches. 
Unable to create aAdvanced Mobile Device Searches, where the criteria was built on group membership as the search type for "member of" & "not member of was missing from the search type validation and would receive the following error 
```
│ Error: expected criteria.0.search_type to be one of ["is" "is not" "like" "not like" "has" "does not have" "greater than" "less than" "greater than or equal" "less than or equal" "matches regex" "does not match regex"], got member of
```
Adding "member of" & "not member of" to the search type validation resolves the issue.
None
[Add screenshots or recordings that demonstrate the …

fix: updated advancedmobiledevicesearches/resource.go to support device group membership criteria

---

internal/resources/macosconfigurationprofilesplist/data_validator.go
internal/resources/macosconfigurationprofilesplistgenerator/data_validator.go

validator was still expecting a list, data model has been moved to a set. 
fixes issues #691 
correctly now throws this error

fix: for plist data validator to support sets rather than lists

---

internal/resources/computer_extension_attribute/resource.go
testing/payloads/jamfpro_computer_extension_attribute/computer_extension_attributes.tf

Jamf 11.18 won't accept a `computer_extension_attribute` with the default `inventory_display_type` of "Extension Attributes", it only works with `EXTENSION_ATTRIBUTES`.
PR submitted in lieu of opening an issue.
First PR and first edit on a Terraform provider, so I may be missing a key step that I'm not aware of.
I don't know how to run these tests locally and I don't have a Jamf environment I can run robust unit tests against.

fix: Conform inventory_display_type default to API
